# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentsync" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "2c8db5aa18528a5524e2dc778625313923fe4f257d113676753bb3b82410cff6"
      url "https://github.com/noah-hrbth/agent-tool-sync/releases/download/v#{version}/agentsync_darwin_amd64.tar.gz",
        verified: "github.com/noah-hrbth/agent-tool-sync/"
    end
    on_arm do
      sha256 "3b94af7936b21ede6e4260cee8bc854138ed316b50c03d79234704502b58a02a"
      url "https://github.com/noah-hrbth/agent-tool-sync/releases/download/v#{version}/agentsync_darwin_arm64.tar.gz",
        verified: "github.com/noah-hrbth/agent-tool-sync/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ebef08ebfa5921d11627138459e15a860cc5e8ac0a8f558652e17e23339dc25f"
      url "https://github.com/noah-hrbth/agent-tool-sync/releases/download/v#{version}/agentsync_linux_amd64.tar.gz",
        verified: "github.com/noah-hrbth/agent-tool-sync/"
    end
    on_arm do
      sha256 "a6a017982521b1251ba8530cf9f91bea1e587602540701a882671212565ba91d"
      url "https://github.com/noah-hrbth/agent-tool-sync/releases/download/v#{version}/agentsync_linux_arm64.tar.gz",
        verified: "github.com/noah-hrbth/agent-tool-sync/"
    end
  end

  name "agentsync"
  desc "Sync AI tool configs (rules, skills, agents, commands) across Claude Code, Cursor, OpenCode, Gemini CLI, and more."
  homepage "https://github.com/noah-hrbth/agent-tool-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentsync"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    agentsync keeps your AI tool configs (rules, skills, agents, commands)
    in one canonical source and syncs them to Claude Code, Cursor,
    OpenCode, Gemini CLI, Codex CLI, and Zed.

    Getting started (project scope):
      1. cd into your project, then:
           agentsync init
      2. Edit .agentsync/AGENTS.md. Add files under .agentsync/rules/,
         .agentsync/skills/, .agentsync/agents/, .agentsync/commands/.
      3. Sync to all enabled tools:
           agentsync sync          # headless one-way sync
           agentsync               # interactive TUI

    Personal defaults across every project (user scope):
           agentsync init --global    # canonical at ~/.agentsync/
           agentsync sync  --global   # syncs to user-level tool dirs

    Project scope writes to <repo>/.<tool>/...; user scope (--global, -g)
    writes to ~/.<tool>/... where supported. The two layers stack.

    Commands:
      agentsync                   Launch TUI (press 'g' to toggle scope)
      agentsync init              Scaffold .agentsync/
      agentsync sync              Headless sync; non-zero on divergence
      agentsync status            Print sync status for every file
      agentsync version           Print version

    Flags: --workspace <path>, -g/--global

    Docs: https://github.com/noah-hrbth/agent-tool-sync
  EOS
end
